//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vgather.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactList2
    {
        public string UserId { get; set; }
        public string ContactName { get; set; }
        public string ContactNumber { get; set; }
    
        public virtual invitation2 invitation2 { get; set; }
    }
}
