//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vgather.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedBackForm
    {
        public string UserId { get; set; }
        public string Ques1 { get; set; }
        public string Rating { get; set; }
        public string Description { get; set; }
    
        public virtual AdminFeedbackForm AdminFeedbackForm { get; set; }
    }
}
