//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vgather.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant
    {
        public Nullable<int> Registration_ID { get; set; }
        public Nullable<int> Event_ID { get; set; }
        public string EventName { get; set; }
        public string CompanyName { get; set; }
        public string Email { get; set; }
        public string Contactnumber { get; set; }
        public string participantName { get; set; }
        public int participantsPaymentID { get; set; }
    
        public virtual EventBooking EventBooking { get; set; }
        public virtual Registration Registration { get; set; }
    }
}
