//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vgather.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public string Company_Name { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public string Contact_Email { get; set; }
        public string Address { get; set; }
        public string Phone_no { get; set; }
        public string Certification { get; set; }
        public int serviceID { get; set; }
    }
}
